/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M S I
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);

    }

    void hapuslayar() {
        //  txtantrian.setText(null);
        txtnamacus1.setText(null);
        combomenu.setSelectedItem(null);
        txtharga.setText(null);
        txtjumlah.setText(null);
        txttotalharga.setText(null);
        txtuang.setText(null);
        txtkembali.setText(null);
        txttanggal.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combomenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnkembalian = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txttotalharga = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtjantrian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        txtuang = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        txtnamacus1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnhapus1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(106, 106, 229)));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 106, 229));
        jLabel2.setText("Nama Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, -1));

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 106, 229));
        jLabel3.setText("kembalian");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        combomenu.setBackground(new java.awt.Color(51, 102, 255));
        combomenu.setForeground(new java.awt.Color(255, 255, 255));
        combomenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----pilihan Menu------", "Hubba boba", "Tea Top", "Tea Party Club" }));
        combomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomenuActionPerformed(evt);
            }
        });
        jPanel1.add(combomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 170, 30));

        tabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(51, 102, 255))); // NOI18N
        tabel.setForeground(new java.awt.Color(102, 102, 255));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Nama", "Menu", "Harga", "Jumlah", "Total Harga", "uang", "kembalian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 600, 140));

        btnkembalian.setBackground(new java.awt.Color(51, 102, 255));
        btnkembalian.setForeground(new java.awt.Color(255, 255, 255));
        btnkembalian.setText("Kembalian");
        btnkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 120, 30));

        btnHitung.setBackground(new java.awt.Color(102, 102, 255));
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 106, 229));
        jLabel4.setText(" Total Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));
        jPanel1.add(txttotalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 170, 30));
        jPanel1.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 160, 30));

        jPanel2.setBackground(new java.awt.Color(106, 106, 229));
        jPanel2.setForeground(new java.awt.Color(106, 106, 229));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JUMLAH ANTRIAN");

        txtjantrian.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtjantrian.setText("\t\t");
        txtjantrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjantrianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(25, Short.MAX_VALUE)
                    .addComponent(txtjantrian, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(txtjantrian, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(268, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 480));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 106, 229));
        jLabel7.setText("Tanggal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(106, 106, 229));
        jLabel9.setText("Harga");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        txtkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(106, 106, 229));
        jLabel10.setText("Jumlah");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(106, 106, 229));
        jLabel11.setText("uang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 170, 30));

        txtuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuangActionPerformed(evt);
            }
        });
        jPanel1.add(txtuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 170, 30));

        btnsave.setBackground(new java.awt.Color(102, 102, 255));
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Simpan");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 90, 30));

        btnedit.setBackground(new java.awt.Color(102, 102, 255));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 90, 30));

        btnbatal.setBackground(new java.awt.Color(102, 102, 255));
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 90, 30));

        txtnamacus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamacus1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtnamacus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 106, 229));
        jLabel6.setText(" Nama Pemesan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 130, -1));

        btnhapus1.setBackground(new java.awt.Color(102, 102, 255));
        btnhapus1.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus1.setText("Selesai");
        btnhapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void btnkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalianActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(txtharga.getText());
        int jumlah = Integer.parseInt(txtjumlah.getText());
        int uang = Integer.parseInt(txtuang.getText());
        try {
            Queue th = new Queue();
            th.kembalian(harga, jumlah, uang);
            txtkembali.setText(" " + th.kembalian(harga, jumlah, uang));

           
        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_btnkembalianActionPerformed

    private void txtjantrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjantrianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjantrianActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(txtharga.getText());
        int jumlah = Integer.parseInt(txtjumlah.getText());
        try {
            Queue th = new Queue();
            th.hitung(harga, jumlah);
            txttotalharga.setText(" " + th.hitung(harga, jumlah));
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }


    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembaliActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtkembaliActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void txtuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuangActionPerformed

    private void combomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomenuActionPerformed
        // TODO add your handling code here:

        int pilihan = combomenu.getSelectedIndex();
        switch (pilihan) {
            case 1:
                txtharga.setText("15000");
                break;

            case 2:
                txtharga.setText("25000");
                break;

            case 3:
                txtharga.setText("30000");

                break;
            default:

        }
    }//GEN-LAST:event_combomenuActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int tab = tabel.getSelectedRow();
        txttanggal.setText(tabel.getValueAt(tab, 0).toString());
        txtnamacus1.setText(tabel.getValueAt(tab, 1).toString());
        combomenu.setSelectedItem(tabel.getValueAt(tab, 2).toString());
        txtharga.setText(tabel.getValueAt(tab, 3).toString());
        txtjumlah.setText(tabel.getValueAt(tab, 4).toString());
        txttotalharga.setText(tabel.getValueAt(tab, 5).toString());
        txtuang.setText(tabel.getValueAt(tab, 6).toString());
        txtkembali.setText(tabel.getValueAt(tab, 7).toString());


    }//GEN-LAST:event_tabelMouseClicked

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2ComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        tabel.setModel(tbl);
    }//GEN-LAST:event_jPanel1ComponentShown

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        // int nomor_antri=Integer.parseInt(txtantrian.getText());
        String nama_pemesan = this.txtnamacus1.getText();
        String nama_menu = (String) combomenu.getSelectedItem();
        int harga = Integer.parseInt(txtharga.getText());
        int jumlah = Integer.parseInt(txtjumlah.getText());
        String total_harga = this.txttotalharga.getText();
        int uang = Integer.parseInt(txtuang.getText());
        String kembalian = this.txtkembali.getText();
        String tanggal = this.txttanggal.getText();
       
        tbl.addRow(new Object[]{
            txttanggal.getText(), txtnamacus1.getText(), combomenu.getSelectedItem(), txtharga.getText(), txtjumlah.getText(),
            txttotalharga.getText(), txtuang.getText(), txtkembali.getText()
        });
        tabel.setModel(tbl);

        txttanggal.setText("");
        //  txtantrian.setText("");
        txtnamacus1.setText("");
        combomenu.setSelectedItem("");
        txtharga.setText("");
        txtjumlah.setText("");
        txttotalharga.setText("");
        txtuang.setText("");
        txtkembali.setText("");

        //Deklarasi
        Queue save = new Queue();

        save.insert(nama_pemesan, nama_menu, harga, jumlah, total_harga, uang, kembalian, tanggal);
        txttanggal.requestFocus();
        txtjantrian.setText(" " + tabel.getRowCount());

    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtnamacus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamacus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamacus1ActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        hapuslayar();

    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        Queue newQueue = new Queue();
        //newQueue.dequeue();
        if (tabel.getSelectedRow() == 0) {
            // if(tabel.getRowCount()==0){
            newQueue.dequeue();
            //newQueue.display();
            model.removeRow(tabel.getSelectedRow());
            // }
        } else {
            JOptionPane.showMessageDialog(null, "Dahulukan antrian awal");
        }
        //  newQueue.display();
        txtjantrian.setText(" " + tabel.getRowCount());
    }//GEN-LAST:event_btnhapus1ActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        if (tabel.getSelectedRow() == -1) {
            if (tabel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tidak Ada Data Dalam Tabel");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih Data Yang Akan Diubah");
            }
        } else {
            model.setValueAt(txttanggal.getText(), tabel.getSelectedRow(), 0);
            //  model.setValueAt(txtantrian.getText(), tabel.getSelectedRow(), 1);
            model.setValueAt(txtnamacus1.getText(), tabel.getSelectedRow(), 1);
            model.setValueAt(combomenu.getSelectedItem(), tabel.getSelectedRow(), 2);
            model.setValueAt(txtharga.getText(), tabel.getSelectedRow(), 3);
            model.setValueAt(txtjumlah.getText(), tabel.getSelectedRow(), 4);
            model.setValueAt(txttotalharga.getText(), tabel.getSelectedRow(), 5);
            model.setValueAt(txtuang.getText(), tabel.getSelectedRow(), 6);
            model.setValueAt(txtkembali.getText(), tabel.getSelectedRow(), 7);

        }
        Queue edit = new Queue();
    //    edit.display();

        hapuslayar();

    }//GEN-LAST:event_btneditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    public void Add() {
        tbl.addRow(new Object[]{
            txttanggal.getText(), txtnamacus1.getText(), combomenu.getSelectedItem(), txtharga.getText(), txtjumlah.getText(),
            txttotalharga.getText(), txtuang.getText(), txtkembali.getText()
        });
        tabel.setModel(tbl);

        txttanggal.setText("");
        //  txtantrian.setText("");
        txtnamacus1.setText("");
        combomenu.setSelectedItem("");
        txtharga.setText("");
        txtjumlah.setText("");
        txttotalharga.setText("");
        txtuang.setText("");
        txtkembali.setText("");
    }

    int baris = 0;
    static Object kolom[] = {"Tanggal", "Nama Pemesan", "Nama Menu", "Harga", "jumlah", "Total Harga", "uang", "kembalian"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus1;
    private javax.swing.JButton btnkembalian;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> combomenu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjantrian;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtnamacus1;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttotalharga;
    private javax.swing.JTextField txtuang;
    // End of variables declaration//GEN-END:variables
}
